#!/bin/sh
echo "                                                          "
echo "             ...Skin successful installed.                "
echo "                                                          "